name: google_reverse_geocoding
description: A Very Good Project created by Very Good CLI.
version: 0.2.0+1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dev_dependencies:
  build_runner: ^2.4.11
  freezed: ^3.2.3
  json_serializable: ^6.8.0
  mocktail: ^1.0.4
  test: ^1.26.2
  very_good_analysis: ^10.0.0

dependencies:
  dio: ^5.0.2
  freezed_annotation: ^3.1.0
  json_annotation: ^4.9.0
